"""Pydantic schemas for request/response serialization."""

from __future__ import annotations

from pydantic import BaseModel, Field


# ─── Auth ────────────────────────────────────────────────────────────────────

class UserCreate(BaseModel):
    username: str = Field(min_length=3, max_length=50)
    email: str
    password: str = Field(min_length=6)
    display_name: str = ""


class UserLogin(BaseModel):
    username: str
    password: str


class UserResponse(BaseModel):
    id: int
    username: str
    email: str
    display_name: str
    is_active: bool

    model_config = {"from_attributes": True}


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: UserResponse


# ─── Strategy Preferences ────────────────────────────────────────────────────

class StrategyPrefUpdate(BaseModel):
    strategy_id: str
    is_active: bool = True
    mastery_level: str = "learning"  # learning | practicing | mastered
    notes: str = ""


class StrategyPrefResponse(BaseModel):
    id: int
    strategy_id: str
    is_active: bool
    mastery_level: str
    notes: str

    model_config = {"from_attributes": True}


# ─── Trades ──────────────────────────────────────────────────────────────────

class TradeCreate(BaseModel):
    session_date: str
    strategy_id: str
    instrument: str = "NQ"
    direction: str
    entry_price: float
    stop_price: float
    target_price: float
    entry_time: str = ""
    notes: str = ""


class TradeUpdate(BaseModel):
    exit_price: float | None = None
    result: str | None = None  # WIN | LOSS | SCRATCH
    pnl: float | None = None
    r_multiple: float | None = None
    exit_time: str | None = None
    notes: str | None = None


class TradeResponse(BaseModel):
    id: int
    session_date: str
    strategy_id: str
    instrument: str
    direction: str
    entry_price: float
    stop_price: float
    target_price: float
    exit_price: float | None
    result: str
    pnl: float
    r_multiple: float
    notes: str
    entry_time: str
    exit_time: str

    model_config = {"from_attributes": True}


# ─── Journal ─────────────────────────────────────────────────────────────────

class JournalCreate(BaseModel):
    session_date: str
    entry_type: str  # premarket | intraday | postmarket | review
    content: str


class JournalUpdate(BaseModel):
    content: str


class JournalResponse(BaseModel):
    id: int
    session_date: str
    entry_type: str
    content: str
    created_at: str
    updated_at: str

    model_config = {"from_attributes": True}


# ─── Bot API Keys ────────────────────────────────────────────────────────────

class BotKeyCreate(BaseModel):
    name: str
    instruments: str = "NQ"


class BotKeyResponse(BaseModel):
    id: int
    api_key: str
    name: str
    instruments: str
    is_active: bool

    model_config = {"from_attributes": True}


# ─── Signals (for dashboard + bots) ─────────────────────────────────────────

class StrategyState(BaseModel):
    """Current state of a single strategy."""

    strategy_id: str
    state: str  # INACTIVE | WATCHING | ARMED | FIRED | DONE | BLOCKED
    direction: str | None = None
    entry_price: float | None = None
    stop_price: float | None = None
    target_price: float | None = None
    current_pnl: float | None = None
    trailing_stop: float | None = None
    block_reason: str | None = None
    condition_progress: dict = Field(default_factory=dict)
    historical_wr: float | None = None
    historical_pf: float | None = None


class MarketContext(BaseModel):
    """Current market state snapshot."""

    instrument: str = "NQ"
    current_price: float = 0.0
    current_time: str = ""
    phase: int = 0  # 0=pre, 1=first_hour, 2=mid, 3=pm
    day_type: str = "UNKNOWN"
    day_type_confidence: float = 0.0
    bias: str = "NEUTRAL"
    ib_high: float | None = None
    ib_low: float | None = None
    ib_range: float | None = None
    vwap: float | None = None
    poc: float | None = None
    vah: float | None = None
    val: float | None = None
    pdh: float | None = None
    pdl: float | None = None
    prior_poc: float | None = None
    ema20: float | None = None
    ema50: float | None = None
    ema200: float | None = None
    rsi14: float | None = None
    atr14: float | None = None
    adx14: float | None = None
    cvd: float | None = None
    tpo_shape: str | None = None
    dpoc: float | None = None
    dpoc_direction: str | None = None
    regime: str | None = None


class TradeIdea(BaseModel):
    """A proactive trade idea generated by the system."""

    id: str
    strategy_id: str
    confidence: str  # high | medium | low
    direction: str
    entry_price: float
    stop_price: float
    target_price: float
    r_reward: float
    rationale: str
    evidence_for: list[dict] = Field(default_factory=list)
    evidence_against: list[dict] = Field(default_factory=list)
    agent_verdict: str | None = None  # TAKE | SKIP | REDUCE_SIZE
    agent_reasoning: str | None = None
    status: str = "developing"  # developing | ready | fired | expired


class SignalEvent(BaseModel):
    """A signal event pushed to bots via REST/WebSocket."""

    signal_id: str
    timestamp: str
    instrument: str
    strategy_id: str
    direction: str
    state: str  # ARMED | FIRED | CLOSED
    entry_price: float
    stop_price: float
    target_price: float
    metadata: dict = Field(default_factory=dict)


class LiveSnapshot(BaseModel):
    """Full state pushed to dashboard via WebSocket."""

    timestamp: str
    market: MarketContext
    strategies: list[StrategyState]
    trade_ideas: list[TradeIdea]
    positions: list[dict] = Field(default_factory=list)
    session_pnl: float = 0.0
    risk_rules: dict = Field(default_factory=dict)
