#!/usr/bin/env python3
from __future__ import annotations
"""
Validate and inspect ROCKIT training pairs generated by /generate-training-pairs skill.

Training pairs are generated by Claude directly via the skill (no API cost).
This script validates the output, reports statistics, and checks quality.

Usage:
    uv run python scripts/generate_training_pairs.py --validate data/training_pairs/training_2026-03-02.jsonl
    uv run python scripts/generate_training_pairs.py --validate-all          # Validate all training pair files
    uv run python scripts/generate_training_pairs.py --stats                 # Summary stats across all files
    uv run python scripts/generate_training_pairs.py --dry-run               # Count available snapshots
    uv run python scripts/generate_training_pairs.py --dry-run --days 5      # Count for N days

Note:
    To generate training pairs, use the /generate-training-pairs skill in Claude Code.
    The API generation mode is still available with --generate (requires ANTHROPIC_API_KEY).
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path

try:
    import anthropic
    HAS_ANTHROPIC = True
except ImportError:
    HAS_ANTHROPIC = False

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT_DIR = PROJECT_ROOT / "data" / "json_snapshots"
OUTPUT_DIR = PROJECT_ROOT / "data" / "training_pairs"
PROMPT_PATH = PROJECT_ROOT / "configs" / "prompts" / "rockit_system_prompt.md"
SCHEMA_PATH = PROJECT_ROOT / "configs" / "prompts" / "output_schema.json"

# --------------------------------------------------------------------------- #
# Pricing (for --generate mode cost tracking)
# --------------------------------------------------------------------------- #
INPUT_COST_PER_1K = 0.015
OUTPUT_COST_PER_1K = 0.075

# --------------------------------------------------------------------------- #
# Time-phase validation
# --------------------------------------------------------------------------- #
TIME_PHASE_RULES = {
    "or_play":              ("09:30", True),
    "ib_read":              ("10:00", True),
    "day_type_call":        ("10:30", True),
    "strategy_assessment":  ("10:00", True),
    "value_area_play":      ("10:30", True),
    "tpo_remarks":          ("10:00", True),
}

THINKING_STEP_ACTIVATION = {
    "step_1_context":  "00:00",
    "step_2_structure":"09:30",
    "step_3_flow":     "09:30",
    "step_4_levels":   "00:00",
    "step_5_day_type": "10:30",
    "step_6_setups":   "10:30",
    "step_7_risk":     "10:30",
}


def time_to_minutes(t: str) -> int:
    """Convert HH:MM to minutes since midnight."""
    h, m = t.split(":")
    return int(h) * 60 + int(m)


def load_system_prompt() -> str:
    if not PROMPT_PATH.exists():
        print(f"ERROR: System prompt not found at {PROMPT_PATH}")
        sys.exit(1)
    return PROMPT_PATH.read_text(encoding="utf-8")


def load_output_schema() -> dict:
    if not SCHEMA_PATH.exists():
        print(f"ERROR: Output schema not found at {SCHEMA_PATH}")
        sys.exit(1)
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def get_snapshot_files(days: int | None = None) -> list[Path]:
    files = sorted(SNAPSHOT_DIR.glob("deterministic_*.jsonl"))
    if days is not None:
        files = files[-days:]
    return files


def load_snapshots(filepath: Path, sample_times: list[str] | None = None,
                   max_per_day: int | None = None) -> list[dict]:
    snapshots = []
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            snap = json.loads(line)
            if sample_times and snap.get("current_et_time") not in sample_times:
                continue
            snapshots.append(snap)
            if max_per_day and len(snapshots) >= max_per_day:
                break
    return snapshots


def validate_output(output: dict, snapshot: dict, schema: dict) -> list[str]:
    """Validate the LLM output against schema and time-phase rules."""
    errors = []
    current_time = snapshot.get("current_et_time", "00:00")
    current_mins = time_to_minutes(current_time)

    # Required top-level fields
    for field in schema.get("required", []):
        if field not in output:
            errors.append(f"Missing required field: {field}")

    # Thinking steps
    thinking = output.get("thinking", {})
    if isinstance(thinking, dict):
        for step in ["step_1_context", "step_2_structure", "step_3_flow",
                      "step_4_levels", "step_5_day_type", "step_6_setups",
                      "step_7_risk"]:
            if step not in thinking:
                errors.append(f"Missing thinking.{step}")
            else:
                step_time = THINKING_STEP_ACTIVATION.get(step, "00:00")
                step_mins = time_to_minutes(step_time)
                value = thinking[step]
                if current_mins < step_mins and not str(value).startswith("NA"):
                    errors.append(
                        f"thinking.{step} should be 'NA — ...' before {step_time}, "
                        f"but got content at {current_time}"
                    )
    else:
        errors.append("thinking must be an object")

    # Time-phase rules
    for field, (earliest, _) in TIME_PHASE_RULES.items():
        earliest_mins = time_to_minutes(earliest)
        value = output.get(field)
        if value is None:
            continue
        if current_mins < earliest_mins:
            if isinstance(value, str) and value.startswith("NA"):
                continue
            elif isinstance(value, dict):
                errors.append(
                    f"{field} should be 'NA — ...' before {earliest}, "
                    f"got object at {current_time}"
                )

    # Array fields
    for arr_field in ["evidence", "what_could_go_wrong"]:
        val = output.get(arr_field)
        if val is not None:
            if not isinstance(val, list):
                errors.append(f"{arr_field} must be an array")
            elif len(val) == 0:
                errors.append(f"{arr_field} must have at least 1 item")

    # day_type_call structure (post 10:30)
    dt_call = output.get("day_type_call")
    if dt_call is not None and current_mins >= time_to_minutes("10:30"):
        if isinstance(dt_call, dict):
            for req in ["classification", "evidence", "skew", "morph_watch"]:
                if req not in dt_call:
                    errors.append(f"day_type_call.{req} missing")
            det_type = (snapshot.get("inference", {})
                        .get("day_type", {}).get("type", ""))
            llm_type = dt_call.get("classification", "")
            if det_type and llm_type and det_type.lower() not in llm_type.lower():
                errors.append(
                    f"day_type_call.classification '{llm_type}' doesn't match "
                    f"deterministic day_type '{det_type}'"
                )

    # one_liner length
    one_liner = output.get("one_liner", "")
    if isinstance(one_liner, str) and len(one_liner) > 150:
        errors.append(f"one_liner too long: {len(one_liner)} chars (max ~120)")

    # Strategy stat accuracy
    output_str = json.dumps(output)
    if "Mean Reversion VWAP" in output_str or "mean_reversion" in output_str.lower():
        if not any(w in output_str for w in ["0.91", "LOSING", "losing", "unreliable", "negative"]):
            errors.append(
                "Mean Reversion VWAP mentioned but missing warning about "
                "negative expectancy (PF 0.91)"
            )

    return errors


def estimate_cost(input_tokens: int, output_tokens: int) -> float:
    return (input_tokens / 1000 * INPUT_COST_PER_1K +
            output_tokens / 1000 * OUTPUT_COST_PER_1K)


# --------------------------------------------------------------------------- #
# Commands
# --------------------------------------------------------------------------- #

def cmd_validate(filepath: str):
    """Validate an existing training pairs JSONL file."""
    schema = load_output_schema()
    path = Path(filepath)
    if not path.exists():
        print(f"ERROR: File not found: {filepath}")
        sys.exit(1)

    total = 0
    valid = 0
    issues = []

    with open(path, "r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            total += 1
            try:
                pair = json.loads(line)
            except json.JSONDecodeError as e:
                issues.append(f"Line {line_no}: JSON parse error: {e}")
                continue

            if "input" not in pair or "output" not in pair:
                issues.append(f"Line {line_no}: Missing 'input' or 'output' key")
                continue

            val_errors = validate_output(pair["output"], pair["input"], schema)
            if val_errors:
                t = pair["input"].get("current_et_time", "?")
                issues.append(f"Line {line_no} ({t}): {len(val_errors)} issues")
                for e in val_errors:
                    issues.append(f"  - {e}")
            else:
                valid += 1

    print(f"\nValidation: {valid}/{total} pairs valid")
    if issues:
        print(f"\nIssues ({len(issues)}):")
        for issue in issues[:50]:
            print(f"  {issue}")
        if len(issues) > 50:
            print(f"  ... and {len(issues) - 50} more")


def cmd_validate_all():
    """Validate all training pair files in output dir."""
    files = sorted(OUTPUT_DIR.glob("training_*.jsonl"))
    if not files:
        print("No training pair files found in data/training_pairs/")
        return

    schema = load_output_schema()
    grand_total = 0
    grand_valid = 0

    for path in files:
        total = 0
        valid = 0
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                total += 1
                try:
                    pair = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if "input" not in pair or "output" not in pair:
                    continue
                val_errors = validate_output(pair["output"], pair["input"], schema)
                if not val_errors:
                    valid += 1

        status = "OK" if valid == total else f"WARN ({total - valid} issues)"
        print(f"  {path.name}: {valid}/{total} valid  {status}")
        grand_total += total
        grand_valid += valid

    print(f"\nTotal: {grand_valid}/{grand_total} pairs valid across {len(files)} files")


def cmd_stats():
    """Show summary statistics across all training pair files."""
    files = sorted(OUTPUT_DIR.glob("training_*.jsonl"))
    if not files:
        print("No training pair files found in data/training_pairs/")
        return

    total_pairs = 0
    by_time = {}
    by_day_type = {}
    dates = []

    for path in files:
        date = path.stem.replace("training_", "")
        dates.append(date)
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    pair = json.loads(line)
                except json.JSONDecodeError:
                    continue
                total_pairs += 1
                t = pair.get("input", {}).get("current_et_time", "?")
                by_time[t] = by_time.get(t, 0) + 1

                dt = (pair.get("input", {}).get("inference", {})
                      .get("day_type", {}).get("type", "N/A"))
                by_day_type[dt] = by_day_type.get(dt, 0) + 1

    print(f"Training Pairs Summary")
    print(f"  Files:      {len(files)}")
    print(f"  Dates:      {dates[0]} to {dates[-1]}")
    print(f"  Total pairs: {total_pairs}")
    print(f"\n  By time:")
    for t in sorted(by_time.keys()):
        print(f"    {t}: {by_time[t]}")
    print(f"\n  By day type:")
    for dt in sorted(by_day_type.keys()):
        print(f"    {dt}: {by_day_type[dt]}")


def cmd_dry_run(days: int | None, sample_times: list[str] | None, max_per_day: int | None):
    """Count available snapshots without processing."""
    system_prompt = load_system_prompt()
    snapshot_files = get_snapshot_files(days)
    if not snapshot_files:
        print("ERROR: No snapshot files found in data/json_snapshots/")
        sys.exit(1)

    total_snapshots = 0
    for snap_file in snapshot_files:
        snaps = load_snapshots(snap_file, sample_times, max_per_day)
        date_str = snap_file.stem.replace("deterministic_", "")
        print(f"  {date_str}: {len(snaps)} snapshots")
        total_snapshots += len(snaps)

    print(f"\n  Total snapshots available: {total_snapshots}")
    print(f"  Use /generate-training-pairs skill to generate (no API cost)")

    # Also show API cost estimate for comparison
    avg_snapshot_chars = 5000
    avg_input_tokens = (len(system_prompt) + avg_snapshot_chars) // 4
    avg_output_tokens = 1500
    total_cost = estimate_cost(
        avg_input_tokens * total_snapshots,
        avg_output_tokens * total_snapshots
    )
    print(f"  (API equivalent cost would be: ${total_cost:.2f})")


def cmd_generate_api(args):
    """Generate training pairs via Opus API (fallback for batch processing)."""
    if not HAS_ANTHROPIC:
        print("ERROR: anthropic package required. Install with: uv pip install anthropic")
        sys.exit(1)

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY environment variable not set")
        sys.exit(1)

    system_prompt = load_system_prompt()
    schema = load_output_schema()
    client = anthropic.Anthropic(api_key=api_key)

    sample_times = None
    if args.sample_times:
        sample_times = [t.strip() for t in args.sample_times.split(",")]

    snapshot_files = get_snapshot_files(args.days)
    if not snapshot_files:
        print("ERROR: No snapshot files found")
        sys.exit(1)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    total_pairs = 0
    total_cost = 0.0

    for snap_file in snapshot_files:
        date_str = snap_file.stem.replace("deterministic_", "")
        output_file = OUTPUT_DIR / f"training_{date_str}.jsonl"
        snapshots = load_snapshots(snap_file, sample_times, args.max_per_day)
        print(f"\n{date_str}: {len(snapshots)} snapshots")

        with open(output_file, "w", encoding="utf-8") as f:
            for snapshot in snapshots:
                user_msg = (
                    "Analyze this deterministic market snapshot. "
                    "Respond with JSON matching the output schema.\n\n"
                    f"```json\n{json.dumps(snapshot, indent=2)}\n```"
                )
                try:
                    response = client.messages.create(
                        model="claude-opus-4-20250514",
                        max_tokens=4096,
                        system=system_prompt,
                        messages=[{"role": "user", "content": user_msg}],
                    )
                    text = "".join(
                        b.text for b in response.content if b.type == "text"
                    ).strip()
                    if text.startswith("```"):
                        lines = text.split("\n")
                        lines = [l for l in lines if not l.strip().startswith("```")]
                        text = "\n".join(lines)

                    output = json.loads(text)
                    cost = estimate_cost(
                        response.usage.input_tokens, response.usage.output_tokens
                    )
                    total_cost += cost

                    pair = {
                        "input": snapshot,
                        "output": output,
                        "metadata": {
                            "session_date": date_str,
                            "current_et_time": snapshot["current_et_time"],
                            "cost_usd": cost,
                            "generated_at": datetime.now().isoformat(),
                            "generator": "opus-api",
                        }
                    }
                    f.write(json.dumps(pair, ensure_ascii=False) + "\n")
                    total_pairs += 1
                    print(f"  {snapshot['current_et_time']} OK (${cost:.3f})")

                except Exception as e:
                    print(f"  {snapshot['current_et_time']} ERROR: {e}")

    print(f"\nDone: {total_pairs} pairs, ${total_cost:.2f} total")


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main():
    parser = argparse.ArgumentParser(
        description="Validate and inspect ROCKIT training pairs"
    )
    parser.add_argument(
        "--validate", type=str, default=None,
        help="Validate a training pairs JSONL file"
    )
    parser.add_argument(
        "--validate-all", action="store_true",
        help="Validate all training pair files"
    )
    parser.add_argument(
        "--stats", action="store_true",
        help="Show summary statistics"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Count available snapshots"
    )
    parser.add_argument(
        "--generate", action="store_true",
        help="Generate via Opus API (fallback — prefer /generate-training-pairs skill)"
    )
    parser.add_argument("--days", type=int, default=None)
    parser.add_argument("--max-per-day", type=int, default=None)
    parser.add_argument("--sample-times", type=str, default=None)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    if args.validate:
        cmd_validate(args.validate)
    elif args.validate_all:
        cmd_validate_all()
    elif args.stats:
        cmd_stats()
    elif args.dry_run:
        sample_times = None
        if args.sample_times:
            sample_times = [t.strip() for t in args.sample_times.split(",")]
        cmd_dry_run(args.days, sample_times, args.max_per_day)
    elif args.generate:
        cmd_generate_api(args)
    else:
        parser.print_help()
        print("\nPreferred: Use /generate-training-pairs skill in Claude Code (no API cost)")


if __name__ == "__main__":
    main()
